# -*- coding: utf-8 -*-
"""Area_price_predict_Linear_Regression_multiple_variable.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FKhYKMcpFtMAJ5RSy5BuwdKAKZjA0o2
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv('/content/Area_price_features.csv')
df

import math
median_bedrroms = math.floor(df.bedrooms.median())
df.bedrooms = df.bedrooms.fillna(median_bedrroms)

reg = linear_model.LinearRegression()
reg.fit(df[['Area','bedrooms','age']],df.price)

reg.predict([[2000,4,20]])